# Generated by Django 4.2.23 on 2025-08-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcs', to='hosts.city')),
            ],
            options={
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='HostStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField()),
                ('host_count', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.city')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.idc')),
            ],
            options={
                'unique_together': {('stat_date', 'city', 'idc')},
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('root_password_encrypted', models.TextField()),
                ('password_updated_at', models.DateTimeField(auto_now=True)),
                ('ping_last_ok', models.BooleanField(default=False)),
                ('ping_last_rtt_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='hosts.city')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='hosts.idc')),
            ],
            options={
                'unique_together': {('hostname', 'ip')},
            },
        ),
    ]
